max_width = 120
hard_tabs = false
tab_spaces = 2
newline_style = "Unix"
wrap_comments = false
normalize_comments = false
merge_derives = true
force_explicit_abi = true
#indent_style = "Block"
#format_strings = false
#comment_width = 80
#empty_item_single_line = true
#struct_lit_single_line = true
#fn_single_line = false
#where_single_line = false
#imports_indent = "Visual"
#imports_layout = "Mixed"
#reorder_extern_crates = true
#reorder_imports = false
#reorder_imported_names = true
#binop_separator = "Front"
#type_punctuation_density = "Wide"
#space_before_colon = false
#space_after_colon = true
#spaces_within_parens_and_brackets = false
#struct_field_align_threshold = 25
#remove_blank_lines_at_start_or_end_of_block = true
#same_line_attributes = true
#fn_args_density = "Tall"
#brace_style = "SameLineWhere"
#trailing_comma = "Vertical"
#blank_lines_upper_bound = 2
#blank_lines_lower_bound = 0
#use_try_shorthand = true
#write_mode = "Overwrite"
#disable_all_formatting = false
#skip_children = false
#report_todo = "Never"
#report_fixme = "Never"
#error_on_line_overflow = false
#error_on_line_overflow_comments = false